import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { statSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Bundle size limit in KB. The sql.js WASM is shipped as a separate file
// (sql-wasm.wasm) and loaded at runtime, so main.js should stay well under
// this threshold. Raise it only with a documented justification.
const BUNDLE_SIZE_LIMIT_KB = 600;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/plugin/main.ts"],
	bundle: true,
	// No binary loader for .wasm — the WASM is shipped as a separate artifact
	// (sql-wasm.wasm) alongside main.js and loaded at runtime via readFileSync.
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();

	const sizeBytes = statSync("main.js").size;
	const sizeKB = (sizeBytes / 1024).toFixed(1);
	console.log(`\nBundle size: ${sizeKB} KB`);

	if (sizeBytes > BUNDLE_SIZE_LIMIT_KB * 1024) {
		console.error(
			`\nERROR: main.js (${sizeKB} KB) exceeds the ${BUNDLE_SIZE_LIMIT_KB} KB size budget.`,
		);
		console.error(
			"Audit new dependencies with: node --input-type=module esbuild.config.mjs --metafile",
		);
		process.exit(1);
	}

	process.exit(0);
} else {
	await context.watch();
}
