// ── ETL report generator ─────────────────────────────────────
//
// Produces:
//   1. Console summary during the run
//   2. Markdown report at output/etl-report.md

import { writeFile } from "fs/promises";

export interface CategoryReport {
	pluginCategory: string;
	ut1Categories: string[];
	ut1Total: number;
	trancoMatches: number;
	qualityRejected: number;
	alreadyCovered: number;
	imported: number;
	cap: number;
}

export interface RejectionStats {
	"excessive-hyphens": number;
	"consecutive-digit-segments": number;
	"suspicious-tld": number;
	"low-value-cctld": number;
	"major-platform-subdomain": number;
	"below-tranco-threshold": number;
	"already-covered": number;
}

export interface ETLReport {
	date: string;
	ut1Hash: string;
	trancoDate: string;
	trancoLimit: number;
	categories: CategoryReport[];
	rejections: RejectionStats;
	totalHandCurated: number;
	totalETL: number;
	totalCombined: number;
}

/**
 * Print a summary table to the console.
 */
export function printConsoleSummary(report: ETLReport): void {
	console.log("\n╔══════════════════════════════════════════════════════╗");
	console.log("║              ETL Category Build Report               ║");
	console.log("╚══════════════════════════════════════════════════════╝\n");

	console.log(`Date:          ${report.date}`);
	console.log(`UT1 hash:      ${report.ut1Hash}`);
	console.log(`Tranco date:   ${report.trancoDate}`);
	console.log(`Tranco limit:  top ${report.trancoLimit.toLocaleString()}\n`);

	// Category table
	const header = "Category".padEnd(15) + "UT1".padStart(7) + "Tranco".padStart(8) +
		"Rejected".padStart(10) + "Covered".padStart(9) + "Added".padStart(7) + "Cap".padStart(6);
	console.log(header);
	console.log("─".repeat(header.length));

	for (const cat of report.categories) {
		console.log(
			cat.pluginCategory.padEnd(15) +
			cat.ut1Total.toString().padStart(7) +
			cat.trancoMatches.toString().padStart(8) +
			cat.qualityRejected.toString().padStart(10) +
			cat.alreadyCovered.toString().padStart(9) +
			cat.imported.toString().padStart(7) +
			cat.cap.toString().padStart(6),
		);
	}

	console.log("─".repeat(header.length));
	console.log(`\nHand-curated:  ${report.totalHandCurated.toLocaleString()}`);
	console.log(`ETL added:     ${report.totalETL.toLocaleString()}`);
	console.log(`Total:         ${report.totalCombined.toLocaleString()}\n`);

	// Rejection breakdown
	console.log("Rejection reasons:");
	for (const [reason, count] of Object.entries(report.rejections)) {
		if (count > 0) {
			console.log(`  ${reason}: ${count}`);
		}
	}
	console.log();
}

/**
 * Write a detailed Markdown report.
 */
export async function writeMarkdownReport(
	reportPath: string,
	report: ETLReport,
): Promise<void> {
	const lines: string[] = [
		"# ETL Category Build Report",
		"",
		`**Generated:** ${report.date}`,
		`**UT1 hash:** \`${report.ut1Hash}\``,
		`**Tranco date:** ${report.trancoDate}`,
		`**Tranco limit:** top ${report.trancoLimit.toLocaleString()}`,
		"",
		"## Summary",
		"",
		`| Metric | Count |`,
		`|--------|-------|`,
		`| Hand-curated patterns | ${report.totalHandCurated.toLocaleString()} |`,
		`| ETL-added patterns | ${report.totalETL.toLocaleString()} |`,
		`| **Total patterns** | **${report.totalCombined.toLocaleString()}** |`,
		"",
		"## Per-Category Breakdown",
		"",
		"| Category | UT1 Domains | Tranco Matches | Quality Rejected | Already Covered | Imported | Cap |",
		"|----------|-------------|----------------|------------------|-----------------|----------|-----|",
	];

	for (const cat of report.categories) {
		lines.push(
			`| ${cat.pluginCategory} | ${cat.ut1Total} | ${cat.trancoMatches} | ` +
			`${cat.qualityRejected} | ${cat.alreadyCovered} | **${cat.imported}** | ${cat.cap} |`,
		);
	}

	lines.push("", "## Rejection Breakdown", "");
	lines.push("| Reason | Count |");
	lines.push("|--------|-------|");
	for (const [reason, count] of Object.entries(report.rejections)) {
		lines.push(`| ${reason} | ${count} |`);
	}

	lines.push(
		"",
		"## Data Sources",
		"",
		"- **UT1 Blacklists:** [Université Toulouse](https://dsi.ut-capitole.fr/blacklists/index_en.php) (CC BY-SA 3.0)",
		"- **Tranco List:** [tranco-list.eu](https://tranco-list.eu/) (Research use)",
		"",
		"---",
		"*This report was generated by `npm run etl:categories`.*",
		"",
	);

	await writeFile(reportPath, lines.join("\n"), "utf-8");
}
